name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Wolfram Engine
        uses: WolframResearch/setup-wolfram-engine@v1
        with:
          wolfram-id: ${{ secrets.WOLFRAM_ID }}
          wolfram-pass: ${{ secrets.WOLFRAM_PASS }}

      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy
      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
      - name: fmt
        run: cargo fmt --all --check
      - name: clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: test
        run: cargo test
      - name: build
        run: cargo build
